apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
  - name: ubuntu-sleeper
    image:  ubuntu-sleeper
    command: ["sleep2.0"] #this overwrites the ENTRYPOINT section in Dockerfile
    args: ["10"] #this will be as if appended value to the docker run command it replaces the CMD section in Dockerfile
