apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: bXlzcWw=  #to be encoded using this command : [echo -n 'mysql' | base64] & the encoded result set as a value to this key instead of plain text
  DB_USER: cm9vdA==   #to be encoded using this command : [echo -n 'root' | base64] & the encoded result set as a value to this key instead of plain text
  DB_PASSWORD: cGFzd3Jk #to be encoded using this command : [echo -n 'paswrd' | base64] & the encoded result set as a value to this key instead of plain text

  #To decode any of the above encoded values of the secret keys under data section use this command : [echo -n '${value}' | base64 --decode]
